{
    'name': 'نرم افزار جامع لیزینگ - اطلاعات پایه عمومی',
    'version': '1.0.0',
    'author': 'بابک جهان بیک لو',
    'sequence': -100,
    'category': '',
    'summary': 'مدیریت اطلاعات پایه عمومی نرم افزار لیزینگ',
    'description': "مدیریت اطلاعات پایه عمومی نرم افزار لیزینگ",
    'depends':['leasing_hesabdari'],
    'data':[
            'security/ir.model.access.csv',
            'data/generaldata_state_data.xml',
            'data/generaldata_city_data.xml',
            'data/generaldata_bank_data.xml',
            'data/generaldata_companytype_data.xml',
#            'data/generaldata_sazman_data.xml',
#            'data/generaldata_companybanch_data.xml',
            'data/generaldata_ownership_data.xml',
#            'reports\generaldata_person_report.xml',
            'views/generaldata_state_view.xml',
            'views/generaldata_city_view.xml',
            'views/generaldata_bank_view.xml',
            'views/generaldata_company_type_view.xml',
            'views/generaldata_companybranch_view.xml',
            'views/generaldata_ownershiptype_view.xml',
            'views/generaldata_person_view.xml',
            'views/generaldata_sazman_view.xml',
            'views/leasing_generaldata_menu.xml',
           ],
    'demo':[],
    'installable': True,
    'auto_install': False,
    'assets':{},
    'application':True,
}