{
    'name': 'نرم افزار جامع لیزینگ - حسابداری',
    'version': '1.0.0',
    'author': 'بابک جهان بیک لو',
    'sequence': -99,
    'category': '',
    'summary': 'مدیریت اطلاعات حسابداری نرم افزار جامع لیزینگ',
    'description': "مدیریت اطلاعات حسابداری نرم افزار جامع لیزینگ",
    'depends':[],
    'data':[
            'security/ir.model.access.csv',
            'data/general_basedef_data.xml',
            'data/account_control_type_data.xml',
            'data/account_group_type_data.xml',
            'data/general_basedef_data.xml',
            'data/accountsoodzian_group_data.xml',
            'data/account_ssubdef_data.xml',
            'data/account_group_data.xml',
            'data/account_ledger_data.xml',
            'data/account_sledger_data.xml',
            'data/account_ssledgertype_data.xml',
            'data/account_ssledger_data.xml',
            'data/account_docdescription_data.xml',
            'data/account_bankaccgroup_data.xml',
#            'data/account_bankacc_data.xml',
            'data/account_monthdefinition_data.xml',
#            'data/account_calendaryear_data.xml',
#            'data/account_calendar_data.xml',
            'views/general_basedef_view.xml',
            'views/account_accountyear_view.xml',
            'views/account_group_view.xml',
            'views/account_ledger_view.xml',
            'views/account_sledger_view.xml',
            'views/account_ssledgertype_view.xml',
            'views/account_ssledger_view.xml',
            'views/account_docdescription_view.xml',
            'views/account_bankaccgroup_view.xml',
            'views/account_bankacc_view.xml',
            'views/account_attachment_view.xml',
            'views/leasing_hesabdari_menu.xml',
            'reports/account_group_report.xml',
            'reports/account_ledger_report.xml',
            'reports/account_sledger_report.xml',
            'reports/account_ssledgertype_report.xml',
            'reports/account_ssledger_report.xml',
            'reports/account_bankaccgroup_report.xml',
            'reports/account_bankacc_report.xml',
    ],
    'demo':[],
    'installable': True,
    'auto_install': False,
    'assets':{},
    'application':True,
}