{
    'name': 'نرم افزار جامع لیزینگ - لیزینگ',
    'version': '1.0.0',
    'author': 'بابک جهان بیک لو',
    'sequence': -97,
    'category': '',
    'summary': 'مدیریت اطلاعات لیزینگ نرم افزار جامع لیزینگ',
    'description': "مدیریت اطلاعات لیزینگ نرم افزار جامع لیزینگ",
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'data/leasingdata_goodcolor_data.xml',
        'data/leasingdata_goodmodel_data.xml',
        'data/leasingdata_taminetebar_data.xml',
        'data/leasingdata_insurancebranch_data.xml',
        'data/leasingdata_karbari_data.xml',
        'data/leasingdata_volumetype_data.xml',
        'data/leasingdata_insurance_data.xml',
        'data/leasingdata_typeghrardad_data.xml',
        'data/leasingdata_tashilattype_data.xml',
        'data/leasingdata_gavahinamehtype_data.xml',
        'data/leasingdata_madarektype_data.xml',
        'data/leasingdata_navaghestype_data.xml',
        'data/leasingdata_enseraf_data.xml',
        'data/leasingdata_controlstatus_data.xml',
        'data/leasingdata_contractstatus_data.xml',
        'data/leasingdata_notetype_data.xml',
        'data/leasingdata_noteresult_data.xml',
        'views/leasingdata_goodcolor_view.xml',
        'views/leasingdata_goodmodel_view.xml',
        'views/leasingdata_taminetebar_view.xml',
        'views/leasingdata_insurancebranch_view.xml',
        'views/leasingdata_karbari_view.xml',
        'views/leasingdata_volumetype_view.xml',
        'views/leasingdata_insurance_view.xml',
        'views/leasingdata_typeghrardad_view.xml',
        'views/leasingdata_tashilattype_view.xml',
        'views/leasingdata_gavahinamehtype_view.xml',
        'views/leasingdata_madarektype_view.xml',
        'views/leasingdata_navaghestype_view.xml',
        'views/leasingdata_enseraf_view.xml',
        'views/leasingdata_controlstatus_view.xml',
        'views/leasingdata_contractstatus_view.xml',
        'views/leasingdata_notetype_view.xml',
        'views/leasingdata_noteresult_view.xml',
        'views/leasing_leasingdata_menu.xml'

    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'assets': {},
    'application': True,
}
