from odoo import models, fields, api
from . import generaldata_state
from . import generaldata_city
from . import generaldata_bank
from . import generaldata_company_type
from . import generaldata_sazman
from . import generaldata_sazmanaddress
from . import generaldata_sazmantahodat
from . import generaldata_sazmantajhizat
from . import generaldata_sazmanazaemodirat
from . import generaldata_sazmanshoraka
from . import generaldata_sazmanmodiramval
from . import generaldata_ownershiptype
from . import generaldata_tashilattype
from . import generaldata_person
from . import generaldata_personaddress
from . import generaldata_persontajhizat
from . import generaldata_personshoraka
from . import generaldata_personazaemodirat
from . import generaldata_personmodiramval
from . import generaldata_persontahodat
from . import generaldata_uom
from . import genraldata_goodtype
from . import genraldata_goodgroup