from odoo import api, fields, models

class Generaldatasazman(models.Model):
    _name = 'leasing_generaldata.generaldata_sazman'
    _rec_name = "sazman_name"

    sazman_oldcode = fields.Integer(string="کد قدیم سازمان", size=10)
    sazman_name = fields.Char(string="نام سازمان", size=100)
    sazman_natcode = fields.Char(string="شناسه ملی", size=11)
    sazman_namamel1 = fields.Char(string="نماینده", size=50)
    sazman_namamel2 = fields.Char(string="فرد کلیدی", size=50)
    sazman_mobile1 = fields.Char(string="تلفن همراه 1", size=11)
    sazman_mobile2 = fields.Char(string="تلفن همراه 2", size=11)
    sazman_economiccode = fields.Char(string="کد اقتصادی", size=20)
    ssledger_id = fields.Many2one("leasing_hesabdari.account_ssledger","حساب تفصیل")
    sazman_image = fields.Image('sazman_image')
    sazman_sodorcityid = fields.Many2one("leasing_generaldata.generaldata_city","محل صدور شناسنامه")
    sodorcity_name1 = fields.Char(related='sazman_sodorcityid.city_name', readonly=True)
    sazman_issueddate = fields.Date(string="تاریخ ثبت" ,default=fields.Date.today())
    sazman_comptypeid = fields.Many2one("leasing_generaldata.generaldata_company_type","نوع شرکت")
    sazman_president = fields.Char(string="نام مدیر عامل", size=50 ,default="  ")
    sazman_tasisdate = fields.Date(string="تاریخ تاسیس" ,default=fields.Date.today())
    sazman_modatsabt = fields.Char(string="مدت ثبت", size=50 ,default="  ")
    sazman_heiatmodirehno = fields.Integer(string="تعداد اعضاء هیئت مدبره", size=10,default=0)
    sazman_roznameh = fields.Char(string="شماره روزنامه رسمی", size=20 ,default="  ")
    sazman_rozndate = fields.Date(string="تاریخ روزنامه رسمی" ,default=fields.Date.today())
    sazman_sarmaye = fields.Float(string="سرمایه شرکت", digits=(20,0), default=0)
    sazman_lastchange = fields.Text(string="آخرین تغییرات",default=" ")
    sazman_typework = fields.Text(string="نوع فعالیت براساس اساسنامه",default=" ")
    sazmanaddress_list = fields.One2many("leasing_generaldata.generaldata_sazmanaddress", "sazman_id")
    sazmantahodat_list = fields.One2many("leasing_generaldata.generaldata_sazmantahodat", "sazman_id")
    sazmantajhizat_list = fields.One2many("leasing_generaldata.generaldata_sazmantajhizat", "sazman_id")
    sazmanshoraka_list = fields.One2many("leasing_generaldata.generaldata_sazmanshoraka", "sazman_id")
    sazmanazaemodirat_list = fields.One2many("leasing_generaldata.generaldata_sazmanazaemodirat", "sazman_id")
    sazmanmodiramval_list = fields.One2many("leasing_generaldata.generaldata_sazmanmodiramval", "sazman_id")
